language: generic
provider: script
os: osx
osx_image: xcode11.2
before_install:
  - bundle update
  - npm install -g yarn --cache-min 999999999
  - npm i -g makeappicon --cache-min 999999999
  - brew install jq >/dev/null
script: bash 1-configure-environment.sh
on:
  branch: master
