language: generic
provider: script
os: osx
osx_image: xcode11.2
podfile: ./ios/Pods
cache:
  yarn: true
  cocoapods: true
  directories:
    - ./ios/Pods
    - ./node_modules
    - $HOME/Library/Caches/Homebrew
before_install:
  - gem update fastlane
  - npm install -g yarn --cache-min 999999999
  - brew cleanup -s
  - brew install graphicsmagick
  - npm i -g makeappicon --cache-min 999999999
  - brew install jq >/dev/null
script: bash 1-configure-environment.sh
on:
  branch: master
